### ISSUE TITLE
Setup wizard - Fatal error

### ISSUE THREAD

**Issue by zvitek** [co-cart/cocart-admin#25]
Hi, I'm trying to install your plugin on a new installation of Wordpress, but I'm getting an error message when setting up the wizard.

```
Fatal error: Uncaught TypeError: WC_Admin_Assets::is_order_meta_box_screen(): Argument #1 ($screen_id) must be of type string, null given, called in /.../wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php on line 277 and defined in /.../wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php:503 Stack trace: #0 /.../wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php(277):
```
`$screen_id` is null

PHP version 8.0.23
WP version 6.0.2
WooCommerce 6.9.1
CoCart - Headless ecommerce 3.7.4

The other plugin is not installed.

Thanks for help

**Comment by seb86** [comment]
Yes a patch was just released to fix that. 😄

**Comment by zvitek** [comment]
Jesus, you're faster than anything I know! 😄 Thank you

**Comment by zvitek** [comment]
It looks like the new version no longer returns an error. 
However, I can't get through the wizard itself.

On the first step, I select "yes" in both selects and click "Let's go".
Then I am redirected to the last step "Ready" where there is basic info etc. From here I can't go back to the administration and when I go back in the history, the settings option in the wizard is still lit.

Further settings etc are not available. Am I getting something wrong?

**Comment by seb86** [comment]
> On the first step, I select "yes" in both selects and click "Let's go".

If you selected "No" on it's not a new store then you would have had an additional step to transfer over the session data for CoCart to read.

The other option installs and activates a CoCart add-on in the background (if not installed already) to add support for CORS without the user needing to filter.

On the ready page, you can access the dashboard via a link at the bottom along with other possible options.

CoCart doesn't really have the need to ask users much to configure things but a settings page will be coming with a couple of new options in the next major release which will also be added to the setup wizard for new users.
